@extends('layout.app')

@section('title', 'Management Report')

@section('page')
<div class="container-fluid">
       
            <h1 class="d-inline-block mb-10">AutoFetch Report</h1>
            <form action="{{ route('reports.sales.autoFetchTransactions') }}" method="get" id="autofetch_filter_form" enctype="multipart/form-data">     
            <div class="row g-5">
                <div class="col-md-4 col-lg-3">
                    <div class="form-group">
                        <label for="trans_date_range">Date</label>
                        <div
                            class="input-group input-daterange"
                            data-control='bsDatepicker'
                            data-date-keep-empty-values="true"
                            data-date-clear-btn="true"
                            id="trans_date_range">
                            <input
                                type="text"
                                name="transaction_from"
                                id="transaction_from"
                                autocomplete="off"
                                value="{{ $inputs['transaction_from'] }}"
                                class="form-control">
                            <div class="input-group-text">to</div>
                            <input
                                type="text"
                                name="transaction_to"
                                autocomplete="off"
                                id="transaction_to"
                                value="{{ $inputs['transaction_to'] }}"
                                class="form-control">
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-lg-2">
                    <div class="form-group">
                        <label for="application_id">Application ID</label>
                        <input
                            type="text"
                            name="application_id"
                            id="application_id"
                            value="{{ $inputs['application_id'] }}"
                            class="form-control">
                    </div>
                </div>
                
                <div class="col-md-4 col-lg-2">
                    <div class="form-group">
                        <label for="transaction_id">Transaction ID</label>
                        <input
                            type="text"
                            name="transaction_id"
                            id="transaction_id"
                            value="{{ $inputs['transaction_id'] }}"
                            class="form-control">
                    </div>
                </div>
    
                <div class="col-12 text-end">
                    <button name="submit" type="submit" class="btn btn-primary btn-sm-block mx-2">Submit</button>
                    
                    <button
                        type="button"
                        data-url="{{ url(route('reports.sales.autoFetchTransactions.export')) }}"
                        data-export="xlsx"
                        class="btn btn-primary btn-sm-block mx-2">
                        Excel
                    </button>
    
                    <button
                        type="button"
                        data-url="{{ url(route('reports.sales.autoFetchTransactions.export')) }}"
                        data-export="pdf"
                        class="btn btn-primary btn-sm-block mx-2">
                        PDF
                    </button>
                </div>
            </div>
        </form>

        <div class="mw-100 p-3 bg-white rounded mt-2">
            <table id="autofetchreport-table" class="table table-striped table-bordered table-hover gx-3 w-100 min-h-300px text-nowrap thead-strong">
                <!-- Generated by Data Table -->
            </table>
        </div>

   
    </div>

@endsection

@push('scripts')
<script>

    $(function() {
        const dateFormat = '{{ dateformat('momentJs') }}';
        const form = document.querySelector('#autofetch_filter_form');
        let formData = new FormData(form);

        const table = $('#autofetchreport-table').DataTable({
            ajax: ajaxRequest({
                url: '{{ route('api.dataTable.autoFetchTransactions') }}',
                method: 'post',
                processData: false,
                contentType: false,
                data: function (data) {
                    return buildURLQuery(data, null, new FormData(document.querySelector('#autofetch_filter_form')))
                },
                eject: true,
            }),
            processing: true,
            serverSide: true,
            dom:
            "<'row'<'col-sm-12 justify-content-end'f>>" +
            "<'mw-100 table-responsive'tr>" +
            "<'row'" +
            "<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'li>" +
            "<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
            ">",
            responsive: true,
            paging: true,
            searchDelay: 500,
            ordering: true,
            order: [[0, 'desc']],
            rowId: 'id',
            columns: [
                {
                    data: 'id',
                    title: 'ID',
                    visible: false,
                    searchable: false
                },
                {data: 'system_id', title: 'System Id'},
                {data: 'type', title: 'Type'},
                {data: 'created_at', title: 'Created Date'},
                {
                    data: 'service_name',
                    title: 'Service',
                    class: 'text-wrap w-300px',
                    width: '300px',
                },
                {
                    data: 'web_user',
                    title: 'Web User',
                    width: '300px',
                    class: 'text-wrap w-300px'
                },
                {
                    data: 'company',
                    title: 'Company',
                    width: '300px',
                    class: 'text-wrap w-300px'
                },
                {
                    data: 'contact_name',
                    title: 'Contact Name',
                    width: '300px',
                    class: 'text-wrap w-300px'
                },
                {data: 'contact_no', title: 'Contact No'},
                {data: 'transaction_id', title: 'Transaction Id'},
                {data: 'application_id', title: 'Application Id'},
                {data: 'service_chg', title: 'Service Chg'},
                {data: 'processing_chg', title: 'Proc. Chg'},
                {data: 'total', title: 'Total'},
                {data: 'invoiced', title: 'Invoiced'},
                {
                    data: null,
                    defaultContent: '',
                    title: '',
                    width: '20px',
                    searchable: false,
                    orderable: false,
                    render: (data, type, row) => {
                        if (row.invoiced == 'Yes') {
                            return null;
                        }
                        
                        return (
                                '<span data-action="delete" data-id="'+row.id+'" title="Delete" class="text-accent mx-1 fa fs-1 p-2 cursor-pointer fa-trash"></span>'
                        )
                    }
                },
            ]
        })

        $('#autofetch_filter_form').on('submit', function (e) {
            e.preventDefault();
            table.ajax.reload();
        })
        

        // Handle the export button click
        $('button[data-export]').on('click', e => {
            const btn = e.target;
            const formData = new FormData(form);
            formData.append('to', btn.dataset.export);
            ajaxRequest({
                url: btn.dataset.url,
                contentType: false,
                processData: false,
                method: 'post',
                data: formData
            }).done((resp, msg, xhr) => {
                if (!resp.redirect_to) {
                    return defaultErrorHandler(xhr);
                }

                window.location = resp.redirect_to;
            }).fail(defaultErrorHandler);
        })

        $('#autofetchreport-table').on('click', '[data-action="delete"]', function (event) {
            var  id = $(this).data('id');
            console.log(id);
            Swal.fire({
                title: 'Are you sure?',
                html: `You are about to delete this entry. <br>This process cannot be reversed!`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (!result.value) {
                    return;
                }
                ajaxRequest({
                    method: 'post',
                    url: "{{route('reports.sales.autoFetchTransactions.destroy', '')}}"+"/"+id,
                    data: {
                        '_method': 'delete'
                    }
                }).done(resp => {
                    if (resp && resp.message) {
                        Swal.fire(resp.message, '', 'success');
                        if ($.fn.DataTable.isDataTable('[data-control="dataTable"]')) {
                            $('[data-control="dataTable"]').DataTable().destroy();
                        }
                        table.ajax.reload();
                        return;
                    }

                    defaultErrorHandler();
                }).fail(defaultErrorHandler);
            })
        });
  
        });
</script>
@endpush