CREATE TABLE `0_payslips` (
    `id` BIGINT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `payroll_id` INT(4) NOT NULL,
    `employee_id` BIGINT(8) NOT NULL,
    `department_id` SMALLINT(2) NOT NULL,
    `designation_id` SMALLINT(2) NOT NULL,
    `monthly_salary` DECIMAL(8,2) NOT NULL,
    `per_day_salary` DECIMAL(8,2) NOT NULL,
    `per_hour_salary` DECIMAL(8,2) NOT NULL,
    `work_hours` TINYINT(1) NOT NULL,
    `holidays_worked` TINYINT(1) DEFAULT 0,
    `weekends_worked` TINYINT(1) DEFAULT 0,
    `minutes_overtime` SMALLINT(3) DEFAULT 0,
    `minutes_late` SMALLINT(3) DEFAULT 0,
    `minutes_short` SMALLINT(3) DEFAULT 0,
    `days_on_leave` DECIMAL(4,2) DEFAULT 0.00,
    `days_off` TINYINT(1) DEFAULT 0,
    `days_absent` TINYINT(1) DEFAULT 0,
    `violations` TINYINT(1) DEFAULT 0,
    `tot_addition` DECIMAL(8,2) DEFAULT 0.00,
    `tot_deduction` DECIMAL(8,2) DEFAULT 0.00,
    `net_salary` DECIMAL(8,2) NOT NULL,
    `is_processed` BOOLEAN DEFAULT 0,
    `processed_by` SMALLINT(6) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    KEY `payroll_id` (`payroll_id`),
    KEY `employee_id` (`employee_id`),
    KEY `department_id` (`department_id`),
    KEY `designation_id` (`designation_id`),
    UNIQUE KEY `uniq_emp_pay` (`payroll_id`, `employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;