ALTER TABLE `0_emp_jobs`
    ADD created_by SMALLINT(6) NULL DEFAULT NULL,
    ADD updated_by SMALLINT(6) NULL DEFAULT NULL,
    ADD created_at TIMESTAMP NULL DEFAULT NULL,
    ADD updated_at TIMESTAMP NULL DEFAULT NULL;